### ISSUE TITLE
LV-VIS training dataset

### ISSUE THREAD

**Issue by ghost** [haochenheheda/LVVIS#5]
Hi, great job!  I made statistics on the LVVIS training set and found some issues:

1. 'partition'=0,1 is base categories, 'partition'=2,3 is novel categories. What is the difference between 0 and 1?
2. The size of some images and annotations in ‘train_instances.json’ does not match the actual image size. 
3. The paper states that there are 641 base categories and 555 novel categories, but I found that there are 1021 categories with annotations in ‘train_instances.json’, far more than 641. Why are there novel categories of annotations for training set?
4. Only 528 base categories have annotations, and 113 basic categories don‘t have annotations?

**Comment by haochenheheda** [comment]
1. partition= 0 (from coco), 1 (from lvis base), 2 (from lvis rare), 3 (new category).
2. Thank you for pinpointing this issue, we will fix those videos.
3. Actually, the training set is newly split from the original val set after rebuttal, as per the suggestion of reviewers. That's why it contains annotations of novel categories. We are now working on video-based training with LV-VIS training set, and we find that category-wise training with LV-VIS training set brings marginal improvement. Maybe it is because after we remove the novel categories of annotations in the training set, the total number of training annotations drops a lot 
4. The number of categories are counted from the whole dataset (train+val+test), thereby each one may contain a subset of the category list
